### ISSUE TITLE
Income floating text renders as red, not green

### ISSUE THREAD

**Issue by BakaOsaka** [OpenRCT2/OpenLoco#110]
I was playing the scenario "Weatherworld" and created a simple passenger train, which rain between two towns. Upon arriving at a station, the floating money text would appear, but would be red instead of green:

![Incorrect colour](https://i.imgur.com/7UDTKk6.jpg)

**Comment by ItsTheKais** [comment]
That's correct behavior, though? Your company color is red, so your money floaters are red. If you change your color to green, you'll get green floaters. If your floaters weren't your company color, it might not be possible to tell your floaters apart from your competitors'.
