### ISSUE TITLE
Make mountain tool available when adjusting land in-game

### ISSUE THREAD

**Issue by ERRORTEK23** [OpenRCT2/OpenLoco#127]
![teren](https://user-images.githubusercontent.com/36601018/36392867-8507ccea-15ad-11e8-8d91-f173fa4c1ab7.png)

It would be good if she went to edit the country as in the map editor. Then railways would be better in the game. So I've got to make the slides in advance in the editor and figure out where to run the rail.

![land](https://user-images.githubusercontent.com/36601018/36393174-ce00950c-15ae-11e8-8b19-4a6a128fbe07.png)

**Comment by AaronVanGeffen** [comment]
Yes, making the mountain tool available in the in-game landscaping tool is something we did for OpenRCT2 as well. We should get to this eventually.

**Comment by jgottula** [comment]
Seems reasonable to me.

That's gonna be one hell of an expensive landscape operation though, given the cost of modifying land in Locomotion (compared to the fairly cheap land modification in RCT1+2, for example).

**Comment by YetiWiz** [comment]
The in-game landscaping tool has a much smaller maximum size compared to the scenario editor, increasing that limit would also be a good idea. In fact, a lot of other editor features like planting forests would be nice as well.
