### ISSUE TITLE
Crashes when changing resolution

### ISSUE THREAD

**Issue by wopian** [OpenRCT2/OpenLoco#129]
Clicking in the dropdown causes the game to crash (seems to fail getting the correct dimensions as it shows the max int value)

![](https://i.imgur.com/QsFXfum.png)

Haven't built it from source yet, so don't have any meaningful information besides the access violation:
<details>
<summary>Exception</summary>
Unhandled exception at 0x004C003A in openloco.exe: 0xC0000005: Access violation reading location 0x0114B004.
</details><br>
 
| Version | OS
| -------- | ---
| 18.02    | W10 Pro 16299

**Comment by AaronVanGeffen** [comment]
This is a known issue — it's in the release notes. ;)

**Comment by AaronVanGeffen** [comment]
No longer happens as of #192 :)
