### ISSUE TITLE
Did you guys remove the ability to drive trains?

### ISSUE THREAD

**Issue by Crashcast-E** [OpenRCT2/OpenLoco#145]
One of my favorite features of locomotion was the ability to press insert, type "DRIVER," then release it to be able to drive the trains. However, in openloco, when I press insert, NOTHING HAPPENS! Did you guys remove it? And if you did, can you like, not?

**Comment by IntelOrca** [comment]
Not intentionally.

**Comment by Crashcast-E** [comment]
Any chance you guys can fix it? I loved the driver feature.

**Comment by duncanspumpkin** [comment]
It's a bug. It will get fixed eventually. We will likely break quite a few things along the way. We can't test everything.
