### ISSUE TITLE
Unable to save game

### ISSUE THREAD

**Issue by legitimatename** [OpenRCT2/OpenLoco#147]
Built OpenLoco on two different Arch Linux machines. The game seems to run fine, but when I try to save it displays the error "unable to save". Nevertheless, a file with the name of the savegame is created, but it cannot be loaded. I can provide more details if you tell me what you need to know and how I can obtain that information.
Thanks for the work you invest in OpenLoco.

**Comment by AaronVanGeffen** [comment]
I believe this has already been resolved in the mean time — I am able to save fine on Arch Linux. :)
