### ISSUE TITLE
Game crash when opening the finance window.

### ISSUE THREAD

**Issue by PhiliThunder** [OpenRCT2/OpenLoco#157]
OS: Windows 10 64bit
Version: 18.02

This is not a consistent crash, but sometimes when i open the finance window by clicking my money, the game crashes. I have tested it for a bit and it may only happen when the game speed is set to pause as you click it.
Also i have only had it happen on original scenarios. (Haven't tested much on my own scenarios)

**Comment by C3805** [comment]
I've noticed this too, mainly when I go to purchase trains. At random occurrences, the game will pause and then crash.

**Comment by AaronVanGeffen** [comment]
I believe this has this been fixed by bbe87775426c52433fd6c8f7da7b21514b3e5599. Could you confirm this is the case?
