### ISSUE TITLE
Linking during build fails on Void Linux

### ISSUE THREAD

**Issue by jtl999** [OpenRCT2/OpenLoco#199]
**OS: Void Linux**  
**Version: Rolling release (similar to Arch)**  
**Commit/Build: caf78f5576456a0d5e16cc131706c8f982b345a9**  

It fails to build on Void Linux, even with `libstdc++-32bit` libraries installed.

**Steps to reproduce:**
1. Attempt build
2. Build fails

**Is the issue reproducible in Locomotion (vanilla)?**

N/A

**Screenshots / Video:**

N/A

**Save game:**

N/A

Here's the (relevant) compiler output

```
[ 75%] Linking CXX executable openloco
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../libstdc++fs.a when searching for -lstdc++fs
/usr/bin/ld: skipping incompatible /usr/lib/libstdc++fs.a when searching for -lstdc++fs
/usr/bin/ld: skipping incompatible /lib/libstdc++fs.a when searching for -lstdc++fs
/usr/bin/ld: cannot find -lstdc++fs
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/openloco.dir/build.make:1026: openloco] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/openloco.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by janisozaur** [comment]
`libstdc++-32bit` should not be required unless you are trying to cross-compile x86 version. You are missing the filesystem part of libstdc++, which is required now.

**Comment by janisozaur** [comment]
It looks like your `libstdc++-32bit` is missing the filesystem part, can you provide list of the files provided by said package and its 64 bit counterpart for comparison?

**Comment by jtl999** [comment]
I'm building this on a 64-bit machine for itself so I don't need to cross compile.

**Comment by jtl999** [comment]
Or is OpenLoco 32-bit only?

**Comment by jtl999** [comment]
```
[jtl@jtl-desktop ~]$ xbps-query -R -f libstdc++
/usr/lib/libstdc++.so.6.0.24
/usr/share/licenses/libstdc++/RUNTIME.LIBRARY.EXCEPTION
/usr/lib/libstdc++.so -> /usr/lib/libstdc++.so.6.0.24
/usr/lib/libstdc++.so.6 -> /usr/lib/libstdc++.so.6.0.24
[jtl@jtl-desktop ~]$ xbps-query -R -f libstdc++-32bit
/usr/lib32/libstdc++.so.6.0.24
/usr/lib32/libstdc++.so -> /usr/lib32/libstdc++.so.6.0.24
/usr/lib32/libstdc++.so.6 -> /usr/lib32/libstdc++.so.6.0.24
```

**Comment by janisozaur** [comment]
Yes, OpenLoco is 32 bit only for now and only x86. It will eventually gain more architecture support, but it's going to take a while.

None of the packages you mentioned provide ` /usr/lib/libstdc++fs.a` mentioned in your earlier report. I would expect the 32 bit package to place similar library under ` /usr/lib32/libstdc++fs.a`.

**Comment by AaronVanGeffen** [comment]
Hmm. Not sure why it could segfault at that point. Does it ask you for the Locomotion directory? Perhaps this is where the error occurs.

The game's first-run procedure is a little error prone at the current stage. Could you try creating your own config dir (`~/.config/OpenLoco`) and `openloco.cfg` file:
```
$ cat ~/.config/OpenLoco/openloco.cfg 
/mnt/Games/Locomotion
0
```

Does that help?

**Comment by jtl999** [comment]
No dice, same error.

On a whim I connected a USB DAC to my desktop since I have onboard audio disabled on my main workstation because reasons and that didn't help either.

**Comment by AaronVanGeffen** [comment]
You'll need an actual game installation directory, not just the CD — the files will be in different locations than OpenLoco expects (and possibly compressed?). That's not the issue here, though, as the game would complain about not being able to find G1.dat.

Could you try running the game through gdb or lldb to see where the segfault originates?

**Comment by jtl999** [comment]
Oh...

In a bit

**Comment by AaronVanGeffen** [comment]
Oof, that early on, huh. Thanks, that's a very helpful backtrace.

Would you happen to be running the game using a tiling window manager?

**Comment by jtl999** [comment]
I am using i3wm, yes.

Is the tiling interfering with the drawing/resize functions?

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenLoco/issues/169

**Comment by jtl999** [comment]
Thanks

**Comment by janisozaur** [comment]
@jtl999 are you able to test #200?

**Comment by jtl999** [comment]
Merged that PR locally.

After some trial and error with the file paths.

![screenshot at 2018-08-02 11-46-28](https://user-images.githubusercontent.com/1234670/43604128-cf080cde-9649-11e8-83ae-08b82e4a31eb.png)

Question:
- Is the lack of music/sound a known issue?
- When I right click pan around the map the mouse speed feels "sluggish" compared to what I remember with Locomotion on Windows years ago.

Maybe if I time I'll try and contribute.

**Comment by AaronVanGeffen** [comment]
> Is the lack of music/sound a known issue?

Yes, it has not been implemented yet. SDL audio is on our wish list!

> When I right click pan around the map the mouse speed feels "sluggish" compared to what I remember with Locomotion on Windows years ago.

Known issue. We've been working on implementing all input functions, rather than relying on Locomotion's routines

**Comment by jtl999** [comment]
Good luck.

I'm busy with uni and other [REDACTED] projects but if I'm less busy I'll take a look.
