### ISSUE TITLE
Game crash after 5-15 minutes

### ISSUE THREAD

**Issue by schl3ck** [OpenRCT2/OpenLoco#210]
**OS:** Windows 8 
**Version:**  18.02 
**Commit/Build:** d2237ea 

Game crashes after some time. The time is random, but it happend within 30 minutes until now. I also cannot say what it triggers. I've turned off break-downs with the file config in appdata and played without sound. With that setting it lasted longer, but only the first time. After the first crash it was back to 5 to 15 minutes approximately (I didn't look on the clock).

Sometimes I was just waiting without any windows open, once I opened a window to buy a bus, other times there were some windows open.

**Steps to reproduce:**
1. Wait

**Is the issue reproducible in Locomotion (vanilla)?**
Once, vanilla crashed the same way in the 2nd tutorial, but I've played over 1 hour now and it didn't.

**Dump file of the process:**
https://1drv.ms/u/s!ArbipCVsHdWrjC__RbGO25k_-1G7

**Comment by AaronVanGeffen** [comment]
I think this may be the same issue as #182
