### ISSUE TITLE
[Bad string] Remove my company from tracks/road baloon (resolved in df4e067)

### ISSUE THREAD

**Issue by Zcooger** [OpenRCT2/OpenLoco#218]
**OS:** Windows 7 Pro x64
**Version:**  18.02
**Commit/Build:**  d2237ea

Bad string

**Is the issue reproducible in Locomotion (vanilla)?**
No, it shows proper string "Remove train from tracks/road"

**Save game:**
Applies to all regular games/saves

![yes](https://user-images.githubusercontent.com/42012614/45322114-97453200-b547-11e8-8a41-585a5cd8d0bf.png)

**Comment by Zcooger** [comment]
I try to launch the savegame or new scenario but after several seconds the game freezes and crashes, when I try to buy a vehicle, move the camera or click "show position" preview arrows.

**Comment by AaronVanGeffen** [comment]
Hmm. That sounds like it might be related to #182 and #210… Could you disable the game's sound in the options screen and try again?

**Comment by Zcooger** [comment]
Now string looks good:
![image](https://user-images.githubusercontent.com/42012614/45323391-42a3b600-b54b-11e8-9a34-bd323c3d82bd.png)
When I hit "mute" ingame nothing bad happens. After unmute/5 seconds the freeze happens again.

**Comment by AaronVanGeffen** [comment]
OK, so this has already been resolved in the mean time, then. We should probably do a release soon, to prevent this sort of confusion… Thanks for reporting, anyway!
