### ISSUE TITLE
Crash after loading savegame, starting new game or buying a new vehicle (when breakdowns_disabled: false)

### ISSUE THREAD

**Issue by Zcooger** [OpenRCT2/OpenLoco#219]
**OS:**  Windows 7 Pro x64
**Version:**  18.02-338
**Commit/Build:**  df4e067

Ingame freeze/crash, does not affect main menu.

**Steps to reproduce:**
1. Load game/Start new game
2. Move camera, open vehicle list, buying new vehicle crashes the process instantly.

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Temporary fix**
Set `breakdowns_disabled: true` in C:\Users\Administrator\AppData\Roaming\OpenLoco\openloco.yml

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/42012614/45322755-7f6ead80-b549-11e8-91e5-7bcf530fb93d.png)
![image](https://user-images.githubusercontent.com/42012614/45322793-8e556000-b549-11e8-9148-a024499dcc47.png)

`Podpis problemu:
  Nazwa zdarzenia problemu:	APPCRASH
  Nazwa aplikacji:	openloco.exe
  Wersja aplikacji:	4.2.170.0
  Sygnatura czasowa aplikacji:	00000000
  Nazwa modułu z błędem:	openloco.exe
  Wersja modułu z błędem:	4.2.170.0
  Sygnatura czasowa modułu z błędem:	00000000
  Kod wyjątku:	c0000005
  Przesunięcie wyjątku:	00049164
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.48
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	891c
  Dodatkowe informacje 2:	891c090fb1bf52976d7024c31ce421fa
  Dodatkowe informacje 3:	478c
  Dodatkowe informacje 4:	478cedb23b9b73b1a544c68e5cf81e65

Przeczytaj w trybie online nasze zasady zachowania poufności informacji:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0415

Jeśli zasady zachowania poufności informacji w trybie online nie są dostępne, przeczytaj nasze zasady zachowania poufności informacji w trybie offline:
  C:\Windows\system32\pl-PL\erofflps.txt
`

**Comment by Zcooger** [comment]
I attach crash dump: https://dbr.ee/GVHe

**Comment by Zcooger** [comment]
Disabling the sound does not fix crash with buying any vehicle.

**Comment by AaronVanGeffen** [comment]
Does disabling vehicle breakdowns fix the issue? You can only do this by editing the `openloco.yml` config file at the moment.

(I know this may seem a little arbitrary, but we're having trouble narrowing down the issue.)

**Comment by Zcooger** [comment]
Vehicle Breakdowns are already disabled. Gonna test with 0.

**Comment by Zcooger** [comment]
Second crash dump: https://dbr.ee/9jXh - Load Save Game > camera move+5 seconds > freeze

**Comment by Zcooger** [comment]
Ok... that was openloco.yml with false option. I've set 1 on openloco.cfg which did not affect new build...

**Comment by AaronVanGeffen** [comment]
> Vehicle Breakdowns are already disabled. Gonna test with 0.

You mentioned you were on df4e0676428ff79aa2230826d5d24765f5786bcb. Note that this version uses `openloco.yml`, not `openloco.cfg`. The former uses `true` and `false`, the latter `1` and `0`. Are you sure you edited the right file?

**Comment by Zcooger** [comment]
Fourth crash dump: https://dbr.ee/L8nR - Crash after ~1 hour gameplay while watching running trains and looking for locomotive.
Music playback working, music oprions button working, vehicle breakdowns disabled. This is the last dump from the same exception c0000005.

**Comment by IntelOrca** [comment]
@Zcooger Is this when buying a new vehicle?

**Comment by Zcooger** [comment]
No, when looking at vehicle buying window (trains), but it suddenly crashed outta nowhere. Probably I was highlighting possible choices of steam locomotives, but it also happens when I want to buy truck.

**Comment by Zcooger** [comment]
What is ankward using "Music Options" button does crash OpenLoco but on the first of my PCs, the second platform does not have this problem and I can use this shortcut.

**Comment by IntelOrca** [comment]
The dumps are fine and I think we have enough now, thanks. I am able to reproduce at least one of the crashes which I am in the process of investigating.

**Comment by AaronVanGeffen** [comment]
This issue should be resolved as of #221. Could you try [the latest build](https://ci.appveyor.com/project/IntelOrca/openloco/build/18.02.2-build1373/artifacts)?

**Comment by AaronVanGeffen** [comment]
You mention these are 'newer' vehicles... Are these custom objects? If so, could you attach them in a zip, too?

**Comment by Zcooger** [comment]
No, I meant vanilla most modern trucks. All testing I did was done on clean version.

**Comment by AaronVanGeffen** [comment]
Fixed by #259.
