### ISSUE TITLE
OpenLoco is looping current music track

### ISSUE THREAD

**Issue by Zcooger** [OpenRCT2/OpenLoco#245]
OpenLoco does not automatically switch between the current song when it is finished - it plays it again instead.

OS: Windows 7 Pro x64
Version: 18.02-422
Commit/Build: 6f8fde1

By the way a little suggestion - Possibility of capturing multimedia keystrokes: previous, play/pause, next.

**Comment by IntelOrca** [comment]
`play_background_music (0x0048A78D)` will need to be implemented to fix this. It checks if the track has ended by looking at the vanilla addresses for the sounds so it doesn't really work now we do audio ourselves.

> By the way a little suggestion - Possibility of capturing multimedia keystrokes: previous, play/pause, next.

I had a look into this. SDL2 do not intercept `WM_APPCOMMAND` and therefore don't support media keys for Windows. You can intercept the messages yourself but whatever reason these messages are not being generated when I press my media keys.

**Comment by Zcooger** [comment]
Alright.
> these messages are not being generated

I may know one reason why... You can check the Human Interface Device Service. In my case I had to start it manually after fresh installation for my additional mouse buttons to work. Otherwise, if you have it running, I don't know what can cause the problem.
