### ISSUE TITLE
Crash when buying vehicles (trains DO work tho)

### ISSUE THREAD

**Issue by Inu90** [OpenRCT2/OpenLoco#257]
**OS:**  Manjaro Linux 4.20.3-1x64
**Version:**  18.02-454
**Commit/Build:**  c42e59c

Buying any truck, bus, boat or plane results on a segmentation fault. Yes, I checked the options mentioned on #219, still crashing

**Steps to reproduce:**
1. Buy vehicle
```

 ./openloco
OpenLoco, v18.02-454 (c42e59c on master, DEBUG)
CreateRectRgn(0, 0, 1, 1)
Create progress bar
SendMessage(PBM_SETRANGE, 256)
SendMessage(PBM_SETSTEP, 1)
SendMessage(PBM_SETPOS, 30)
OpenMutexA(0x1f0001, 0, Locomotion_GSKMUTEX)
CreateMutexA(0x0, 0, Locomotion_GSKMUTEX)
SendMessage(PBM_SETPOS, 40)
Destroy progress bar
Create progress bar
SendMessage(PBM_SETRANGE, 256)
SendMessage(PBM_SETSTEP, 1)
SendMessage(PBM_SETPOS, 60)
SendMessage(PBM_SETPOS, 220)
SendMessage(PBM_SETPOS, 235)
SendMessage(PBM_SETPOS, 250)
Destroy progress bar
tick prematurely ended
Segmentation fault (core dumped)
```

**Is the issue reproducible in Locomotion (vanilla)?**
No, running as intended on wine.

Coredump: https://pastebin.com/77MfqyKf

**Comment by duncanspumpkin** [comment]
This is related to #194. I can't work out why but the y coordinate of where to draw text is getting corrupted.
