### ISSUE TITLE
macOS build crashes as soon as you want to start a scenario

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenLoco#40]
Stack alignment issue, but I don't understand where it comes from. AFAIK I hooked all library calls, yet those don't get mentioned during the crash.

```
* thread #1: tid = 0x2213952, 0xa16bb200 libdyld.dylib`misaligned_stack_error_, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0xa16bb200 libdyld.dylib`misaligned_stack_error_
```

**Comment by IntelOrca** [comment]
It is probably the `esp` jmp stuff that happens, a.k.a. premature tick termination.

**Comment by marijnvdwerf** [comment]
Adding an align attribute indeed fixes it. `[](registers& regs) __attribute__((force_align_arg_pointer)) -> uint8_t {`

**Comment by IntelOrca** [comment]
@marijnvdwerf Is this fixed now?

**Comment by marijnvdwerf** [comment]
Yes, it was tackled in #50
