### ISSUE TITLE
Game graphic broken

### ISSUE THREAD

**Issue by fromthere** [OpenRCT2/OpenLoco#52]
OS : Windows 7
Commit : c71a455

![image](https://user-images.githubusercontent.com/10338434/35396903-55ad9cfc-0231-11e8-91b6-165c4cedac23.png)
Graphics are broken so I cannot test it all.
I use notebook(with 610M nvidia optimus) both graphic modes are not working(intel or nvidia)

**Comment by AaronVanGeffen** [comment]
It looks like you're using the Steam version of the game. When #20 is merged, the problem should be resolved.

**Comment by AaronVanGeffen** [comment]
Could you verify this has been fixed as of d7689098d1d42bb9dd6a613276adc6add0162927?

**Comment by fromthere** [comment]
problem solved. thanks
