### ISSUE TITLE
Feature request: Add option to disable vehicle breakdowns

### ISSUE THREAD

**Issue by cbcb** [OpenRCT2/OpenLoco#81]
To allow for more leisurely play-styles and use of massive fleets of vehicles or trams, there exists a "No Breakdowns" mod for vanilla which disables breakdowns entirely.

It would be nice to have this in OpenLoco, and should be easier to implement than a proper solution like bulk-upgrading tools for your fleet.

**Comment by IntelOrca** [comment]
This has already implemented, but there is currently no UI to change it. It can be changed by editing your openloco.cfg file (found in `%APPDATA%/OpenLoco` or `~/.config/openloco`. Change the second line to 1.
