### ISSUE TITLE
Feature Request: Ability to place fences in game

### ISSUE THREAD

**Issue by CarpetCrumbs** [OpenRCT2/OpenLoco#83]
I've noticed that you can only place fences in scenario editor and not in-game. It's a good scenic object and can be useful if you feel up to making your game look neat (side note: this would also be a good idea for misc buildings)

**Comment by YetiWiz** [comment]
Also, placing them alongside tracks/roads (On the same tile, not the adjacent one). This could be useful for example, when building highways and you want to separate the roads with a barrier in between without leaving a block of space.

**Comment by AaronVanGeffen** [comment]
This has already been implemented by #163.
